bindPort = 49151
vhostHTTPPort = 180
vhostHTTPSPort = 1443

auth.method = "token"
auth.token = "Gl97&0^nJoin&P5ywJi9Q%r1^JT%XOHj"

transport.maxPoolCount = 1
transport.heartbeatTimeout = 30

allowPorts = [ { start = 2000, end = 49000 } ]

webServer.addr = "0.0.0.0"
webServer.port = 49150
webServer.user = "admin"
webServer.password = "admin"

log.to = "./frps.log"
log.level = "info"
log.maxDays = 3
log.disablePrintColor = false
detailedErrorsToClient = true
